/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  cane                                   */
/*      FILE         :  sbrk.h                                 */
/*      DESCRIPTION  :  Header file of sbrk file               */
/*      CPU SERIES   :  SH-2                                   */
/*      CPU TYPE     :  SH7125                                 */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/* size of area managed by sbrk */
#define HEAPSIZE 0x400