/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  cane                                   */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  SH-2                                   */
/*      CPU TYPE     :  SH7125                                 */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize 0x400